export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const SAVE_TASK = 'SAVE_TASK'
export const NEW_TASK = 'NEW_TASK'
export const GRAB_FIRST_TASK = 'GRAB_FIRST_TASK'
export const GRAB_SECOND_TASK = 'GRAB_SECOND_TASK'
export const GRAB_CHANGE_TASKS = 'GRAB_CHANGE_TASKS'